### ISSUE TITLE
 Simple Kerberos failed to load the "kerberos" v3.0.0

### ISSUE THREAD

**Issue by CrtGalitt** [noamokman/express-kerberos#10]
NestedError: Simple Kerberos failed to load the "kerberos" module
    at Object.<anonymous> (C:\USR\POC_LDAP\node_modules\simple-kerberos\src\index.js:12:9)
    at Module._compile (module.js:653:30)
    at Module._compile (C:\USR\poc_ldap\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (C:\USR\poc_ldap\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\USR\POC_LDAP\node_modules\express-kerberos\src\index.js:2:1)
    at Module._compile (module.js:653:30)
    at Module._compile (C:\USR\poc_ldap\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (C:\USR\poc_ldap\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:566:32)
Caused By: TypeError: kerberosModule.Kerberos is not a constructor
    at Object.<anonymous> (C:\USR\POC_LDAP\node_modules\simple-kerberos\src\index.js:9:14)
    at Module._compile (module.js:653:30)
    at Module._compile (C:\USR\poc_ldap\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (C:\USR\poc_ldap\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\USR\POC_LDAP\node_modules\express-kerberos\src\index.js:2:1)
    at Module._compile (module.js:653:30)
    at Module._compile (C:\USR\poc_ldap\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (C:\USR\poc_ldap\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:566:32)

**Comment by noamokman** [comment]
https://github.com/noamokman/simple-kerberos#faq

**Comment by noamokman** [comment]
Also, this project is no longer maintained, PRs welcome
