### ISSUE TITLE
Simple Kerberos failed to load the "kerberos" module

### ISSUE THREAD

**Issue by Jack119911** [noamokman/express-kerberos#3]
I tried to use the middleware as described, but got this error:
```
NestedError: Simple Kerberos failed to load the "kerberos" module
    at Object.<anonymous> (/opt/Dashboard-Express-Server/node_modules/express-kerberos/node_modules/simple-kerberos/lib/index.js:24:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Dashboard-Express-Server/node_modules/express-kerberos/lib/index.js:20:23)
    at Module._compile (module.js:653:30)
Caused By: TypeError: kerberosModule.Kerberos is not a constructor
    at Object.<anonymous> (/opt/Dashboard-Express-Server/node_modules/express-kerberos/node_modules/simple-kerberos/lib/index.js:22:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Dashboard-Express-Server/node_modules/express-kerberos/lib/index.js:20:23)
    at Module._compile (module.js:653:30)

```
Maybe some issue with the dependency on youre other repository simple-kerberos?
Because this project still uses its old version? Just a thought....

**Comment by noamokman** [comment]
Yeah your'e right, I'll update the package an republish

**Comment by Jack119911** [comment]
Thank you for your effort. Please let me know here once its available on npm.

**Comment by Jack119911** [comment]
Now it works, thank you!

**Comment by sikhaarun** [comment]
![image](https://user-images.githubusercontent.com/48405092/54802678-58303000-4c92-11e9-948c-b3ec9a5a2579.png)
still having the same issue

**Comment by noamokman** [comment]
@sikhaarun that's a different error, it looks like kerberos did not install correctly for you.
It's a native module that builds on when you `npm install`

**Comment by JumpAttacker** [comment]
![image](https://user-images.githubusercontent.com/10989729/67861506-66500400-fb31-11e9-8438-79f2e5a97b61.png)

i have this error too

i did install kerberos from here https://www.npmjs.com/package/kerberos

npm install kerberos --unsafe-perm

then type

npm install express-kerberos --unsafe-perm

and got this error now
